name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.11.1.post1
        env:
          CIBW_SKIP: pp*
          CIBW_TEST_COMMAND: python -m unittest discover -f ephem
